
services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-app:1.0
    container_name: rag-application
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
        # Gunicorn configuration
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=2
      - GUNICORN_WORKER_CLASS=gthread
      - GUNICORN_TIMEOUT=120
      - GUNICORN_LOG_LEVEL=info
      - GEMINI_POOL_SIZE=4  # Should be >= workers * threads
    ports:
      - "5000:5000"